# Generated by Django 5.2.7 on 2025-10-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('dinner', 'dinner'), ('other', 'other'), ('lunch', 'lunch'), ('dressing', 'dressing'), ('breakfast', 'breakfast'), ('dessert', 'dessert'), ('snack', 'snack')], max_length=10)),
                ('time_min', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('time_max', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('servings', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('instructions', models.TextField(default='')),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default='', max_length=255)),
                ('amount', models.CharField(default='n/a', max_length=10)),
                ('measurement', models.CharField(choices=[('ml', 'ml'), ('fl oz', 'fl oz'), ('kg', 'kg'), ('pinch', 'pinch'), ('scoop', 'scoop'), ('tsp', 'tsp'), ('cup', 'cup'), ('pint', 'pint'), ('tbsp', 'tbsp'), ('oz', 'oz'), ('L', 'L'), ('lb', 'lb'), ('dash', 'dash'), ('quart', 'quart'), ('g', 'g')], max_length=7)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientgroup')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientgroup',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes'),
        ),
    ]
