# Generated by Django 5.2.7 on 2025-10-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredients_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientgroup',
            name='recipe_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='group_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredientgroup'),
        ),
    ]
