# Generated by Django 5.2.7 on 2025-11-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack'), ('dessert', 'dessert'), ('dressing', 'dressing'), ('other', 'other')], max_length=10)),
                ('time_min', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('time_max', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('servings', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('instructions', models.TextField(default='')),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default='', max_length=255)),
                ('amount', models.CharField(default='', max_length=10)),
                ('measurement', models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('oz', 'oz'), ('lb', 'lb'), ('pinch', 'pinch'), ('dash', 'dash'), ('scoop', 'scoop'), ('ml', 'ml'), ('L', 'L'), ('g', 'g'), ('kg', 'kg'), ('can', 'can')], max_length=7)),
                ('group_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredientgroup')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientgroup',
            name='recipe_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='recipes.recipes'),
        ),
    ]
