# Generated by Django 5.2.7 on 2025-11-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('oz', 'oz'), ('lb', 'lb'), ('pinch', 'pinch'), ('dash', 'dash'), ('scoop', 'scoop'), ('ml', 'ml'), ('L', 'L'), ('g', 'g'), ('kg', 'kg'), ('can', 'can'), ('qty', 'qty')], max_length=7),
        ),
    ]
