# Generated by Django 5.2.7 on 2025-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredients_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='time_max',
            new_name='cook_time_max',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='time_min',
            new_name='cook_time_min',
        ),
        migrations.AddField(
            model_name='recipes',
            name='prep_time',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.CharField(default='', max_length=50),
        ),
    ]
